### ISSUE TITLE
Make documentation more complete

### ISSUE THREAD

**Issue by moshest** [thenativeweb/p2p#1]
Thank you for the great work! I just read the `README.md` file and it's looks awesome!
I have a few question that I couldn't find on the documentation:

  1. How can I register a peer for `getPeerFor` method?
  2. How the process of finding peers works? Is it scalable?
  3. Is all communication made throw `HTTPS` protocol? Is it has support via local routers?

Thank you.

**Comment by goloroden** [comment]
Thanks for your feedback and the compliments, we really appreciate that :-)

Regarding your questions:

1. Basically it works like this: Supposed you have `n` peers that already know each other (in case of `n`=1, the peer at least knows itself). When you start a new peer, it has to `join` an arbitrary one of the existing `n` peers. Then the peers automatically introduce the new peer to the network, so you get a network of `n+1` peers. Then repeat to build larger networks ;-). Once you run `getPeerFor` on an arbitrary peer, the network automatically figures out the peer that is responsible for the given data. For details on how all of this works, see [this paper](https://github.com/thenativeweb/p2p/blob/master/doc/Chord.pdf).

2. Yes, the process is highly scalable and works with logarithmic efforts. Again, for the details see the [aforementioned paper](https://github.com/thenativeweb/p2p/blob/master/doc/Chord.pdf).

3. Yes, the communication is built upon https. What do you mean by "support via local routers"?

**Comment by moshest** [comment]
Without any configuration, tcp servers usually get blocked on home network router. Is it true for this library also?

Thank you.

**Comment by goloroden** [comment]
I'm not perfectly sure if I correctly got your question, but… I think you are wondering about network routers because a peer is a server that needs to be accessed from the outside, and this is usually blocked by routers, unless you open the connection, right?

If so, then right now, yes, p2p has this very issue :-(

**Comment by GochoMugo** [comment]
Qudos!!! This project is interesting to me! I would like to contribute but I do not understand/know where to begin with. Are there any docs/links you could propose that could get me going in the *peer-to-peer* business?

**Comment by goloroden** [comment]
Thanks for your kind words :-)

For a quick start, have a look [at this PDF](https://github.com/thenativeweb/p2p/blob/master/doc/Chord.pdf).
