### ISSUE TITLE
Lol at this module.

### ISSUE THREAD

**Issue by Dillybob92** [thenativeweb/p2p#3]
It's good to know this module requires over 172 dependencies:

![image](https://cloud.githubusercontent.com/assets/10387670/15381528/0fa1ff56-1d35-11e6-8446-532808d9be37.png)

Sorry but, the start up time to require all these is a huge turn off.

**Comment by goloroden** [comment]
We welcome constructive feedback or pull requests, either on why this is an actual problem, or how to get better.

Unfortunately, your issue looks a lot like trolling, hence I'm closing this issue now. I'm sorry if I got this wrong. If so, feel free to reopen the issue and provide more details or a PR.

**Comment by Dillybob92** [comment]
Trolling? There is 172 fucking dependencies. And the start up time to require the module blocks the IO significantly (2-3 seconds) on startup.

**Comment by goloroden** [comment]
As said, feel free to give *constructive* feedback on how to improve this or send a PR.
